server:
  port: 8763
spring:
  application:
    name: eureka-server-8763
eureka:
  client:
    # 不向注册中心拉取注册信息
    fetch-registry: false
    # 不向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server-8761:8761/eureka,http://eureka-server-8762:8762/eureka,http://eureka-server-8763:8763/eureka
