server:
  port: 9000
spring:
  application:
    name: sentinel-9000
  cloud:
    nacos:
      server-addr: localhost:8848
      # nacos服务注册地址
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
    # sentinel配置
    sentinel:
      enabled: true
      # sentinel 控制台地址配置
      transport:
        dashboard: localhost:8888
        # 与dashboard的通信地址, 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
        port: 8719
      log:
        dir: F:\SOFT\Sentinel\log
      # 将sentinel配置持久化至nacos配置
      datasource:
        ds1:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            data-id: ${spring.application.name}
            namespace: eb3d1486-728b-453a-9ee4-9447dc258cbb
            group-id: SENTINEL
            data-type: json
            rule-type: flow

# 开启feign支持sentinel
feign:
  sentinel:
    enabled: true
# 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
